# Language of interface. Supported values: en, ru.
language: en
# Flag to ensure that application is started with dedicated terminal window.
# Required to have "a window" for user to close app and don't duplicate processes.
ensureTerminal: false
# Write "glob" template to your Inecobank "Statement" XML files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
inecobankStatementXmlFilesGlob: demo/Statement*.xml
# Write "glob" template to your Inecobank "statement" XLSX (Excel) files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
inecobankStatementXlsxFilesGlob: demo/statement*.xlsx
# Write "glob" template to your Ameriabank Business "AccountStatement" CSV files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
ameriaCsvFilesGlob: demo/AccountStatement*.csv
# Write "glob" template to your MyAmeria "Statement" XLS files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
myAmeriaAccountStatementXlsxFilesGlob: demo/* account statement *.xls
# Write "glob" template to your MyAmeria "History" XLS files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
myAmeriaHistoryXlsFilesGlob: demo/History *.xls
# Write "glob" template to your Ardshinbank XLSX files received via email.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
ardshinbankXlsxFilesGlob: demo/STATEMENT_*.xlsx
# Write "glob" template to your generic/custom source CSV files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
genericCsvFilesGlob: demo/generic*.csv
# Due to MyAmeria "History" files don't provide any information about accounts
# you need to specify map of your account(s) number (16 digits number) and
# relevant currency 3 letter code.
# Thus all transactions with "Beneficiary account" from this list would be
# understood as an income and amount in account currency would be set.
myAmeriaMyAccounts:
# List of currencies to unconditionally convert transactions into.
# Note that if transactions files don't have enough information about exchange rates
# totals would be incorrect!
convertToCurrencies:
  - AMD
# Flag to output all information about the result.
detailedOutput: false
# Flag to print details for all uncategorized transactions. Skips any other actions.
categorizeMode: false
# Which day of month use as start of the month.
# Sometimes it makes sense to analyze month from the "salary day".
monthStartDayNumber: 1
# Flag to aggregate all transactions with "Details" not matched with "substrings"
# from 'groups' below into single group with name "Unknown".
# Otherwise unknown transactions create new categories with "Details" value name.
timeZoneLocation: Asia/Yerevan
# Which day of month use as start of the month.
# Sometimes it makes sense to analyze month from the "salary day. 
groupAllUnknownTransactions: true
# Groups of categories to match transactions by.
# May contain following keys:
# - substrings: List of substrings to search in transaction's "Details" field.
# - fromAccounts: List of accounts to match in "From Account" field.
# - toAccounts: List of accounts to match in "To Account" field.
groups:
  Cash:
    substrings:
      - ATM
      - Cash withdrawal_e-cheque
      - Կանխիկացում
  Entertainment:
    substrings:
      - AQUATEK
      - EATERY
      - TASHIR PIZZA
      - KARAS
      - PLAY CITY
      - INSTITUTE OF BOTANY
  Groceries:
    substrings:
      - CHEESE MARKET
      - YEREVAN  CITY
      - YEREVAN CITY
      - EVRIKA
      - MARKET
      - FIESTA\19
      - FIX PRICE
      - MAQUR TUN
      - GRAND CANDY
  Health:
    substrings:
      - ARABKIR JMC
      - CRYSTAL DENTAL CLINIC
      - GEGHAMA\ABOVYAN 34 A
      - NAIRI CLINIC
      - WIGMORE
      - VARDANANTS
  Pharmacies:
    substrings:
      - PHARM
      - DIALAB
      - "36.6"
      - NATALI FARM
      - THEOPHARMA
      - GEDEON RICHTER
  Salary:
    substrings:
      - ամսվա աշխատավարձ
      - ԱՄՍՎԱ ԱՇԽԱՏԱՎԱՐՁ
  Subscriptions:
    substrings:
      - GOOGLE
      - SUBSCRIPTION
      - AWS EMEA
      - CLOUD
      - Spotify
  Online shopping:
    substrings:
      - WILDBERRIES
      - OZON.RU
      - TEMU
  Taxi:
    substrings:
      - GG Taxi
      - Yandex Taxi
      - Yandex Go
  Utilities and rent:
    substrings:
      - Kentron View
      - Veolia Jur
      - Electricity
      - VivaCell
      - Ucom
  Transfer between my accounts:
    substrings:
      - Account replenishment
      - Currency exchange
